[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"
remappings = ["CPMMMath=0x2264d1af87E3fbd844fCdbA574B4955B33D9D9D6"]
optimizer = true         
optimizer_runs = 200      
via_ir = true             

[etherscan]
mainnet = { key = "NQ4136G89YVN7WPA1TKBMDNK7UXVD4KV8N" }



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
